### ISSUE TITLE
error: the trait `nickel::middleware::Middleware` is not implemented for the type `fn(&nickel::request::Request<'_, '_>, &mut nickel::response::Response<'_, '_>)

### ISSUE THREAD

**Issue by tarcieri** [nickel-org/nickel.rs#136]
It seems that many old programs and examples do not work because of this?

I am trying to use @rgs1's `more-fixes-for-alpha` branch on 1.0.0-alpha

**Comment by SimonPersson** [comment]
Yes, we believe this to be some sort of bug in the compiler. You can see the workaround in the examples in his fork, basically you just have to store the handler function in a variable before you add it to the router. Alternatively you can use the router macro instead.

We can keep this issue open so that we remember to look into it, hopefully it will just start working again one day.

**Comment by Ryman** [comment]
@tarcieri It's a coercion failure, something about all `fn`s are now unique items and not function pointers unless cast to one. See https://github.com/rust-lang/rust/issues/20178 for more meaningful info.

In this case, if you have a handler `foo`, you can use something like `bar.something(foo as fn(&Request, &mut Response) -> MiddlewareResult);`

**Comment by rgs1** [comment]
Hi @SimonPersson, @Ryman:

So Hyper does something like this to work around the need for casting (rust issue #20178):

```rust
trait Foo {
    fn foo(&self);
}

impl<F> Foo for F where F: Fn() {
    fn foo(&self) {
        self();
        println!("do foo");
    }
}

fn bar() {
    println!("do bar");
}

fn take_foo<F: Foo>(f: F) {
    f.foo();
}

fn main() {
    take_foo(bar);
}
```
This would allow us to work around the need for casting. The only issue that I found when trying to implement this is that when doing it, i.e., for:

```rust
impl<F, R> Middleware for R
    where F: Fn(&Request, &mut Response) -> R, F: Sync + Send + 'static, R: ResponseFinalizer {
    // ....
}
```

it mostly works except that the compiler then complains about conflicting implementations when doing it for:

```rust
impl<F, R> Middleware for R
    where F: Fn(&mut Request, &mut Response) -> R, F: Sync + Send + 'static, R: ResponseFinalizer {
    // ....
}
```
which is, allegedly, almost the same except for the Request being mut. If we could work around this, this might help us clean up the casts (I think!).

Thoughts?

**Comment by Ryman** [comment]
Yeah, I  encountered this early after unboxed closures stabilised a bit in a test branch. Can't have multiple blanket implementations as we do now, as you can imagine that type `Foo` could `impl Fn(&mut Request...` *AND* `impl Fn(&Request...` which would be a coherence issue.

I think we definitely want to move to unboxed closures though, so it will happen, it's just a matter of deciding on what our final API is since we can only choose a single variant. 

With the move to hyper (nearly finished, honest!) it looks like the main handler API will be in the form of either `Fn(&mut Request, Response) -> R` or `Fn(&mut Request, Response)` (no return).  

- a `&mut Request`, as we will want to have the caching on the request
- an owned `Response`, as the response will be stateful (as it's an error to amend headers after the body is already streaming), so the type will change depending on what operations are performed. This was briefly covered in #99 and it just so happens that hyper has solved the same issue so we will just wrap a similar api.
- how to work with the return type accounting for the move requirement and the single blanket impl is pretty much the final bit of the hyper port left, I think I've got a good idea for how to manage it, but if not (or if I don't get to it in the next day or two) I'll push up a PR with the current slightly tedious handlers.

**Comment by rgs1** [comment]
Great, thanks for the reply @Ryman ! Is the port-to-hyper branch available somewhere for the curious ones? :-)

**Comment by Ryman** [comment]
Relevant: https://github.com/rust-lang/rfcs/pull/883

**Comment by Ryman** [comment]
Should no longer be an issue after #197 and e8c74753ebe79a40b1828a712b27d37a489d948a
