### ISSUE TITLE
Error: cannot move out of captured outer variable in an `Fn` closure

### ISSUE THREAD

**Issue by joelmccracken** [nickel-org/nickel.rs#241]
I'm trying to use a variable captured from the outer environment. The full gist showing what I want to do is linked, but I made a small reproducible that illustrates the problem which I will put below.

https://gist.github.com/joelmccracken/bcda083cb1f6caaa090d

reproducible: 
```
#[macro_use] extern crate nickel;
use nickel::Nickel;

fn do_print(s: String) {
    print!("{}", s)
}

fn main() {
    let thing = "hi there".to_string();
    let mut server = Nickel::new();

    server.utilize(router! {
        get "**" => |_req, _res| {
            do_print(thing)
        }
    });

    server.listen("127.0.0.1:6767");
}
```
=> 

```
cargo build
   Compiling simple-log v0.1.0 (file:///Users/joel/Projects/simple-log)
src/main.rs:26:22: 26:27 error: cannot move out of captured outer variable in an `Fn` closure
src/main.rs:26             do_print(thing)
                                    ^~~~~
<nickel macros>:1:1: 1:27 note: in expansion of as_block!
<nickel macros>:10:12: 10:42 note: expansion site
note: in expansion of closure expansion
<nickel macros>:9:6: 10:54 note: expansion site
<nickel macros>:1:1: 10:62 note: in expansion of _middleware_inner!
<nickel macros>:4:1: 4:60 note: expansion site
<nickel macros>:1:1: 7:46 note: in expansion of middleware!
<nickel macros>:11:32: 11:78 note: expansion site
<nickel macros>:1:1: 21:78 note: in expansion of _router_inner!
<nickel macros>:4:1: 4:43 note: expansion site
<nickel macros>:1:1: 4:47 note: in expansion of router!
src/main.rs:24:20: 28:6 note: expansion site
error: aborting due to previous error
Could not compile `simple-log`.

To learn more, run the command again with --verbose.
```

I don't really understand what is going on, because I can see in the rust expansion that the macro is outputting a 'move' in front of this closure.

**Comment by joelmccracken** [comment]
I forgot to mention: as far as I can tell, this seems to be something with the internals of the router! macro. That's why I bring it up here.

**Comment by Ryman** [comment]
Yeah, this error message is pretty poor, would be neat to have more control of it.

There's 2 different types of move when discussing closures:
- moving *into* the closure which is what the `move` keyword is doing to let the closure own the data
- moving *out* of a captured variable, which can only be done in an `FnOnce/FnBox`

Since these handlers need to be called many times they're bound with `Fn` and you can't move out of the data, which is what the call to `do_print` does as it takes `String`. 

To fix this, you should instead take a borrow, which in this case means your function should take `&str`.

Feel free to ask for more clarification.

**Comment by joelmccracken** [comment]
Hey, thanks! That makes sense. Sorry for filing a false issue, and I really appreciate the help -- this has been really frustrating me for a few days.
