### ISSUE TITLE
How to create custom middleware that takes an Arc<Mutex<HashMap<&str, &str>>>

### ISSUE THREAD

**Issue by cburgdorf** [nickel-org/nickel.rs#256]
Ok, I'm halfway through manually implementing auth on a shitty session-in-url-based approach. It's really just for me to learn. It's not going in production. However, I got stuck 1 arm length before the finish line.

I created an `Auth` middleware that basically checks for a session parameter in the URL, and redirects to the login in case it's missing (so it excludes the `/login` and `/login-callback` routes itself for that check).

But now I want to create sessions on the `/login-callback` and obviously I want my `Auth` middleware to not only check for existence of the `?session` param but also if it has a known, valid session set. So I thought, ok, let's just pass it an `Arc<Mutex<HashMap<&str, &str>>>` which I can create from my `main` function and fill with sessions from the `/login-callback` (after I got the OAuth token). But this leads down the lifetime hell path.

Here is what I have

```rust

use std::sync::{Arc, Mutex};
use std::collections::HashMap;

use nickel::*;
use nickel::status::StatusCode;
use hyper::header::{Location};

pub struct Auth<'b> {
    sessions: Arc<Mutex<HashMap<&'b str, &'b str>>>
}

impl<'b> Auth<'b> {
    fn new (sessions: Arc<Mutex<HashMap<&'b str, &'b str>>>) -> Auth<'b> {
        Auth {
            sessions: sessions
        }
    }
}

impl<'b> Middleware for Auth<'b> {
    fn invoke<'a>(&self, req: &mut Request, mut res: Response<'a>) -> MiddlewareResult<'a> {
        println!("going into custom middleware");

        match req.path_without_query() {
            Some(path) if path == "/login" => return Ok(Continue(res)),
            Some(path) if path == "/login-callback" => return Ok(Continue(res)),
            _ => {}
        }


        if let Some(_) = req.query().get("session") {
            println!("auth -> fine");
            Ok(Continue(res))
        }
        else {
            res.set(StatusCode::TemporaryRedirect)
            //update header
            .set(Location("/login".to_owned()));
            //Ok(Halt(res))
            println!("auth -> not fine");
            let stream = try!(res.start());
            Ok(Halt(stream))
        }
    }
}
```

But this then leaves me with an error:

```
src/auth.rs:20:1: 45:2 error: the type `auth::Auth<'b>` does not fulfill the required lifetime
src/auth.rs:20 impl<'b> Middleware for Auth<'b> {
src/auth.rs:21     fn invoke<'a>(&self, req: &mut Request, mut res: Response<'a>) -> MiddlewareResult<'a> {
src/auth.rs:22         println!("going into custom middleware");
src/auth.rs:23 
src/auth.rs:24         match req.path_without_query() {
src/auth.rs:25             Some(path) if path == "/login" => return Ok(Continue(res)),
```

**Comment by cburgdorf** [comment]
I can fix it by using `String` instead of `&str` but I'm actually more interested to learn how I could fix it without reaching out to `String`.

**Comment by Ryman** [comment]
Middleware requires `'static` so you cannot have the lifetime `'b` (until the scoped api exists for real again and then *maybe* hyper may change again. You'll need to either have `&'static str`s or `String`s. in your hashmap. 

Btw, you might want to use a `RwLock` rather than a `Mutex` if the majority usage is going to be reading :)

**Comment by cburgdorf** [comment]
Ah, interesting. 

>until the scoped api exists for real again and then maybe hyper may change again.

What does that refer to? Changes to the way threading works in Rust, I guess?

>Btw, you might want to use a RwLock rather than a Mutex if the majority usage is going to be reading :)

:+1:  thanks, for the extra learning!

**Comment by Ryman** [comment]
What used to be http://doc.rust-lang.org/std/thread/fn.scoped.html would allow you to spawn a thread that could access data on the current stack frame (and therefore could be less than `'static`), it was found to be memory unsafe https://github.com/rust-lang/rust/issues/24292 when things were 'forgotten/leaked' (which curiously lead to `mem::forget` becoming 'safe').

**Comment by cburgdorf** [comment]
So, that means that threads in todays Rust can only contain *references* with `'static` lifetime. But just for me to get a deeper understanding: When I share a `HashMap<String, String>` through facilities such as `Arc<Mutex<T>` across threads, we are also accessing data that isn't on the current stack frame, right?

**Comment by Ryman** [comment]
Kind of yes, I should have been a bit more clear. By having the `'static` lifetime it implies 'not borrowed', so we either own the data, or it's the lifetime of the program (static), the Arc is a shared ownership of this data. The restriction here, is that when sending to another thread, the other thread needs to own all the data it receives, except for references to statics, otherwise you'll get use after frees. The scoped api was a neat trick to allow borrowing from the original thread as long as the spawned thread(s) terminated before the end of a given scope. You should probably check the ownership/borrowing sections in the guide for a refresh, I'm sure my explanation is rather poor (and probably partially wrong!).

> When I share a HashMap<String, String> through facilities such as Arc<Mutex<T> across threads, we are also accessing data that isn't on the current stack frame, right?

To try to answer the question, you aren't accessing data on the original threads stack, yes, but the Arc itself (a pointer to the refcounts and data) would have a copy on the stack of the new thread, pointing to the heap (in most cases).

**Comment by cburgdorf** [comment]
Ah, yes that makes total sense. I tend to forget this kind of nitty gritty knowledge again and again. I'd love to have a reference right into your brain haha ;)
