### ISSUE TITLE
repeat: StaticFilesHandler freezing

### ISSUE THREAD

**Issue by inv2004** [nickel-org/nickel.rs#420]
The situation exactly the same like here: https://github.com/nickel-org/nickel.rs/issues/308

All my app - is just static content from directory: ~4 files is ok, and 5th is hang for ~15secs.
Iron and Rocket are ok in the same situation.

Versions:
rustc 1.24.0-nightly
nickel = "*"

**Comment by jolhoeft** [comment]
Have you tried disabling keep-alives, or increasing the thread count? (Increasing the thread count requires 0.10.1) What platform (windows, linux, mac) are you using?

As a side note `nickel="*"` may prove dangerous. I hope to release nickel-0.11 soon, based on hyper 0.11. This changes the nickel API in breaking ways, so you might not want to automatically upgrade to it. `nickel="0.10"` is probably safer. Since 0.11 will be such a big change, I am tentatively planning on supporting 0.10.x for a while.

**Comment by inv2004** [comment]
I suppose that I did not stick to any framework, that is why I tried iron, rocket, nickel, hyper and 2 more. Unfortunately I did not want to play with all these parameters, because some works with default settings out of the box.
